<?php
namespace Tests\Unit;

use Algorithms\UnionFind\QuickFind;
use Tests\TestCase;

class QuickFindTest extends TestCase
{
    /** @var QuickFind */
    private $quickFind;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->quickFind = new QuickFind();
    }

    public function testGetTarget()
    {
        $assertion = 99;

        $this->quickFind->setTarget($assertion);

        $this->assertCount($assertion, $this->quickFind->getTarget());
    }

    public function testUnion()
    {
        $this->quickFind->setTarget(100);

        $this->quickFind->union(81, 82);
        $this->quickFind->union(83, 84);

        $this->assertFalse($this->quickFind->connected(81, 84));

        $this->quickFind->union(82, 84);
        $this->assertNotFalse($this->quickFind->connected(81, 84));
    }
}
