<?php
namespace Tests\Unit;

use Algorithms\UnionFind\QuickUnion;
use Tests\TestCase;

class QuickUnionTest extends TestCase
{
    /** @var QuickUnion */
    private $quickUnion;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->quickUnion = new QuickUnion();
    }

    public function testGetTarget()
    {
        $assertion = 99;

        $this->quickUnion->setTarget($assertion);

        $this->assertCount($assertion, $this->quickUnion->getTarget());
    }

    public function testUnion()
    {
        $this->quickUnion->setTarget(100);

        $this->quickUnion->union(81, 82);
        $this->quickUnion->union(83, 84);

        $this->assertFalse($this->quickUnion->connected(81, 84));

        $this->quickUnion->union(82, 84);
        $this->assertNotFalse($this->quickUnion->connected(81, 84));
    }
}
