<?php
namespace Tests\Unit;

use Algorithms\UnionFind\QuickFind;
use Tests\TestCase;

class QuickFindTest extends TestCase
{
    /** @var QuickFind */
    private $quickFind;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->quickFind = new QuickFind();
    }

    public function testGetTarget()
    {
        $assertion = 99;

        $this->quickFind->setTarget($assertion);

        $this->assertCount($assertion, $this->quickFind->getTarget());
    }

    public function testUnion()
    {
        $this->quickFind->setTarget(100);

        $this->quickFind->union(81, 82);
        $this->quickFind->union(83, 84);

        $this->assertFalse($this->quickFind->connected(81, 84));

        $this->quickFind->union(82, 84);
        $this->assertNotFalse($this->quickFind->connected(81, 84));
    }

    public function testAll()
    {
        $target = 1000;
        $start = microtime(true);
        $this->quickFind->setTarget($target);

        for ($i = 0; $i < ($target-1); $i++) {
            $this->quickFind->union($i, $i+1);
        }
        $end = microtime(true);
        $spent = $end - $start;
        print_r(PHP_EOL . "一千目標測試中，quick-find花費時間為：{$spent}" . PHP_EOL);
        $this->assertNotFalse($this->quickFind->connected(0, $target-1));
    }

    public function testFind()
    {
        $target = 1000;
        $biggest = 543;

        $this->quickFind->setTarget($target);

        for ($i = 0; $i < $biggest; $i++) {
            $this->quickFind->union($i, $i+1);
        }

        $this->assertEquals($biggest, $this->quickFind->find(3));
    }
}
